# Generated by Django 3.1.7 on 2021-04-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='review',
        ),
    ]
