# Generated by Django 3.1.7 on 2021-05-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_admin_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellermain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Cancelled', 'Cancel Order'), ('Return Requested', 'Request Return')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='marked_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        
        migrations.AddField(
            model_name='product',
            name='seler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.sellermain'),
        ),
    ]
